name: Metrics
on:
  # Workflow manually
  workflow_dispatch:
  #schedule:
    # Schedule updates (at the end of every day)
    # - cron: "0 0 * * *"
  #push:
    #branches:
      #- main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          extras_css: | # Make it prettier
            h2 { margin: 2px 5px 6px !important; }

      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.calendar.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          extras_css: | # Make it prettier
            h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_other: true
          plugin_languages_sections: most-used
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_details: bytes-size, percentage
          extras_css: | # Make it prettier
            h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }

      - name: Reactions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.reactions.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_reactions: yes
          extras_css: | # Make it prettier
            h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }

      - name: Repositories
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.repositories.svg
          base: ""
          repositories_skipped: nguyenngoclongdev/nguyenngoclongdev, nguyenngoclongdev/nguyenngoclongdev.github.io, nguyenngoclongdev/cdn
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_pinned: 6
          plugin_repositories_starred: 100
          plugin_repositories_random: 100
          plugin_repositories_order: pinned, starred, featured, random
          extras_css: | # Make it prettier
            h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }

      # - name: Recently starred
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.stars.svg
      #     base: ""
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     plugin_stars: yes
      #     plugin_stars_limit: 3
      #     extras_css: | # Make it prettier
      #       h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }

      # - name: Topics
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.topics.svg
      #     base: ""
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     plugin_topics: yes
      #     plugin_topics_limit: 0
      #     plugin_topics_mode: icons
      #     extras_css: | # Make it prettier
      #       h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }

      - name: Followup
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.followup.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_followup: true
          plugin_followup_sections: repositories
          extras_css: | # Make it prettier
            h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }

      # - name: Recent activity
      #   uses: jamesgeorge007/github-activity-readme@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     MAX_LINES: 10

      # - name: Profile summary
      #   uses: vn7n24fzkq/github-profile-summary-cards@release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
      #   with:
      #     USERNAME: ${{ github.repository_owner }}
      #     BRANCH_NAME: "main"
      #     UTC_OFFSET: 7
      #     EXCLUDE: ""
      #     AUTO_PUSH: true

      # - name: People
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.people.svg
      #     base: ""
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     plugin_people: yes
      #     plugin_people_identicons: yes
      #     plugin_people_limit: 24
      #     plugin_people_shuffle: yes
      #     plugin_people_size: 30
      #     plugin_people_types: followers, sponsors, members, contributors, stargazers, watchers
      #     extras_css: | # Make it prettier
      #       h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }

      # - name: Achievements
      #   uses: lowlighter/metrics@96dde98a034ab75fec7884f9161bc12759275d36
      #   with:
      #     filename: metrics.achievements.svg
      #     base: ""
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     plugin_achievements: true  # Show achievements
      #     plugin_achievements_threshold: C  # Show all unlocked achievements
      #     plugin_achievements_secrets: true  # Include secret achievements
      #     plugin_achievements_limit: 0  # All that can fit
      #     plugin_achievements_display: compact  # Compact layout
      #     extras_css: |  # Make it prettier
      #       h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }
