name: Metrics
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.calendar.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes

      - name: Reactions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.reactions.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_reactions: yes

      - name: Repositories
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.repositories.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_featured: vs-asdf, vs-data-sync, vs-terminal-keeper, step-definition-generator, gherkin-editor, vs-diff, pkgscan, vscode-fs-browserify,
          plugin_repositories_order: featured, pinned, starred, random
