name: Metrics
on:
  # Workflow manually
  workflow_dispatch:
  schedule:
    # Schedule updates (at the end of every day)
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.calendar.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes

      - name: Reactions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.reactions.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_reactions: yes

      - name: Repositories
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.repositories.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_pinned: 6
          plugin_repositories_starred: 100
          plugin_repositories_random: 100
          plugin_repositories_order: pinned, starred, featured, random

      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
