name: Sync Profile

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync Profile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync Profile
        run: |
          git clone https://$GITHUB_ACTOR:${{secrets.gh_secret}}@github.com/nguyenngoclongdev/nguyenngoclongdev.github.io.git
          cd nguyenngoclongdev.github.io
          git config user.name LongNguyen
          git config user.email nguyenngoclong.dev@outlook.com
          mv ../README.md README.md
          git add README.md
          git commit -m "Sync README.md"
          git push
